### ISSUE TITLE
No way to use library with unifi controller

### ISSUE THREAD

**Issue by Kolia56** [nickovs/unificontrol#39]
Hello,
I'm running Unifi Controller 7.2.97-18705-1 on a CloudKey (firmware v1.1.19)
This program run on a Windows 10 machine with Python 3.12.0 
```python
from unificontrol import UnifiClient
client = UnifiClient(host='xxx.xxx.xxx.xxx', username='xxx', password='yyyyyy')
```
triggers the following exception
```
Exception ignored in: <function PinningHTTPSAdapter.__del__ at 0x000001DB23C41580>
Traceback (most recent call last):
  File "C:\Users\NicolasRabaté\AppData\Roaming\Python\Python312\site-packages\unificontrol\pinned_requests.py", line 85, in __del__
  File "C:\Program Files\Python312\Lib\tempfile.py", line 478, in __getattr__
AttributeError: '_io.TextIOWrapper' object has no attribute 'delete'
```
What could be the reason? Thank you

**Comment by nickovs** [comment]
It appears that there was some change to the deletion semantics on Windows in Python 3.12. I don't have a Windows machine on which to try things, but I will take a look and see if I can work out what is going on.

**Comment by Kolia56** [comment]
> It appears that there was some change to the deletion semantics on Windows in Python 3.12. I don't have a Windows machine on which to try things, but I will take a look and see if I can work out what is going on.

Thank you very much to take care of this issue. Let me know if I can be of any help on this matter for further testing, for instance.

**Comment by Vasilich** [comment]
any chance to look at it?
I use it on HomeAssistantOS (Linux based), so no Windows involved, but I get the same exception message as topicstarter,

**Comment by thefueley** [comment]
Hi, I'm getting the same error as @Kolia56 and @Vasilich. I am on Fedora and running Python 3.13.5. Relevant code snippet below. I am using a `config.ini` for creds.
```
import os
import configparser
from urllib.parse import urlparse
import urllib3
from unificontrol.unifi import UnifiClient

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

script_dir = os.path.dirname(os.path.abspath(__file__))
config_file_path = os.path.join(script_dir, 'config.ini')

config = configparser.ConfigParser(interpolation=None)
config.read(config_file_path)

UNIFI_URL = config['unifi']['controller_url']
UNIFI_USER = config['unifi']['controller_username']
UNIFI_PASS = config['unifi']['controller_password']
UNIFI_SITE = config['unifi']['controller_site']

def test_unifi_login():
    try:
        print("Attempting to connect to UniFi Controller...")
        
        parsed_url = urlparse(UNIFI_URL)
        unifi_host = parsed_url.hostname
        unifi_port = parsed_url.port if parsed_url.port else 443
        
        client = UnifiClient(
            host=unifi_host,
            username=UNIFI_USER,
            password=UNIFI_PASS,
            port=unifi_port,
            site=UNIFI_SITE,
            cert='FETCH_CERT'
        )

        sites = client.list_sites()
        
        print("Success")
        print(f"Found sites: {sites}")

    except Exception as e:
        print(f"Error connecting to UniFi Controller: {e}")

if __name__ == "__main__":
    test_unifi_login()

```

**Error message:**
```
Error connecting to UniFi Controller: HTTPSConnectionPool(host='X.X.X.X', port=443): Max retries exceeded with url: /api/self/sites (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: invalid CA certificate (_ssl.c:1028)')))
Exception ignored in: <function PinningHTTPSAdapter.__del__ at 0x7f8d4b379800>
Traceback (most recent call last):
  File "$HOME/code/PROJECT/venv/lib/python3.13/site-packages/unificontrol/pinned_requests.py", line 85, in __del__
    if (not self._ca_cert_temp.delete and os.path.isfile(self._ca_cert_temp.name)):
  File "$HOME/.asdf/data/installs/python/3.13.5/lib/python3.13/tempfile.py", line 494, in __getattr__
    a = getattr(file, name)
AttributeError: '_io.TextIOWrapper' object has no attribute 'delete'
```
